<!DOCTYPE
        >
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lab02</title>
</head>
<body>
<script type="text/javascript">

    // Question 01 -   Promises/Asynchronous and callbacks

    //Create a function that returns a value after 1 second (return inside a setTimeout).

    //getValueAfter5 function accepts a function called callback
    function getValueAfter5(callback) {
        let value1 = 0;
        let value2 = 0;
        setTimeout(function () {
            value1 = 10;
            value2 = 20;
            callback(value1, value2)
        }, 5000);
    }

    //calling getValueAfter5 function by passing a function as a parameter
    getValueAfter5(function (value1, value2) {
        const total = value1 + value2;
        console.log("callback function worked and value is :" + total);
    })


    //simple method which accepts a function as an argument
    function getValue(callback) {
        let value = 0;
        setTimeout(function () {
            value = 10;
            callback(value)
        }, 5000);

    }

    //method which accepts two arguments which are value and a function
    function getNewValue(value, callback) {
        setTimeout(function () {
            callback(value * 1000);
        }, 10000);
    }

    //calling getValue method by passing a function
    getValue(function (value) {
        //calling getNewValue function inside getValue method
        getNewValue(value, function (newValue) {
            console.log("New value is " + newValue);
        })
    });


    //Now return a promise instead of accepting the callback.


    function promiseGetValue() {
        let value = 0;
        //resolve -> success
        //reject - > error
        return new Promise(function (resolve, reject) {
            setTimeout(function () {
                value = 10;
                resolve(value);
            }, 1000);
        });
    }

    function promiseGetNewValue(value) {
        return new Promise(function (resolve, reject) {
            setTimeout(function () {
                resolve(value * 100);
            }, 1000);
        })
    }

    promiseGetValue().then(function (value) {
        console.log("promise function worked and value is :" + value);
    })

    function setValue(value) {
        return value + 9999;
    }

    //chain promises
    promiseGetValue().then(function (value) {
        return promiseGetNewValue(value);
    }).then(function (value) {
        return setValue(value);
    }).then(function (value) {
        console.log("value at last is:" + value);
    }).then(function () {
        console.log("promise chain testing");
    }).catch(function (err){
        //exception handling in promises
        console.log(err)
    });

    //resolve method can only accept 1 argument, cannot return multiple values from a promise as well
    //also when creating the promise 'reject' is not mandatory


</script>

</body>
</html>